KeyboardConfig = function(){return {"67108874": {"control": "ViewMenu_ShowSamplers",
 "group": "[KeyboardShortcuts]"},
 "67108875": {"control": "ViewMenu_ShowMicrophone",
 "group": "[KeyboardShortcuts]"},
 "67108876": {"control": "ViewMenu_ShowVinylControl",
 "group": "[KeyboardShortcuts]"},
 "13": {"control": "reloop_exit",
 "group": "[Channel1]"},
 "67108878": {"control": "ViewMenu_ShowEffects",
 "group": "[KeyboardShortcuts]"},
 "15": {"control": "beatsync",
 "group": "[Channel2]"},
 "16": {"control": "loop_in",
 "group": "[Channel2]"},
 "17": {"control": "loop_out",
 "group": "[Channel2]"},
 "18": {"control": "reloop_exit",
 "group": "[Channel2]"},
 "19": {"control": "flanger",
 "group": "[Channel2]"},
 "24": {"control": "beatloop_4_toggle",
 "group": "[Channel1]"},
 "25": {"control": "loop_halve",
 "group": "[Channel1]"},
 "26": {"control": "loop_double",
 "group": "[Channel1]"},
 "67108891": {"control": "OptionsMenu_RecordMix",
 "group": "[KeyboardShortcuts]"},
 "67108892": {"control": "OptionsMenu_EnableVinyl1",
 "group": "[KeyboardShortcuts]"},
 "67108893": {"control": "OptionsMenu_EnableVinyl2",
 "group": "[KeyboardShortcuts]"},
 "67108894": {"control": "OptionsMenu_EnableVinyl3",
 "group": "[KeyboardShortcuts]"},
 "67108895": {"control": "OptionsMenu_EnableVinyl4",
 "group": "[KeyboardShortcuts]"},
 "32": {"control": "loop_double",
 "group": "[Channel2]"},
 "134217764": {"control": "LoadSelectedTrackAndPlay",
 "group": "[PreviewDeck1]"},
 "33554470": {"control": "reverse",
 "group": "[Channel1]"},
 "39": {"control": "fwd",
 "group": "[Channel1]"},
 "33554472": {"control": "cue_set",
 "group": "[Channel1]"},
 "41": {"control": "cue_default",
 "group": "[Channel1]"},
 "42": {"control": "crossfader_down",
 "group": "[Master]"},
 "33554475": {"control": "crossfader_up_small",
 "group": "[Master]"},
 "44": {"control": "back",
 "group": "[Channel2]"},
 "67108909": {"control": "passthrough",
 "group": "[Channel2]"},
 "33554478": {"control": "cue_set",
 "group": "[Channel2]"},
 "47": {"control": "cue_default",
 "group": "[Channel2]"},
 "49": {"control": "talkover",
 "group": "[Microphone]"},
 "52": {"control": "hotcue_1_activate",
 "group": "[Channel1]"},
 "33554485": {"control": "hotcue_2_clear",
 "group": "[Channel1]"},
 "54": {"control": "hotcue_3_activate",
 "group": "[Channel1]"},
 "33554487": {"control": "hotcue_4_clear",
 "group": "[Channel1]"},
 "56": {"control": "filterLowKill",
 "group": "[Channel1]"},
 "100663353": {"control": "LibraryMenu_NewCrate",
 "group": "[KeyboardShortcuts]"},
 "33554490": {"control": "hotcue_1_clear",
 "group": "[Channel2]"},
 "59": {"control": "hotcue_2_activate",
 "group": "[Channel2]"},
 "60": {"control": "hotcue_3_activate",
 "group": "[Channel2]"},
 "33554442": {"control": "bpm_tap",
 "group": "[Channel1]"},
 "11": {"control": "loop_in",
 "group": "[Channel1]"},
 "12": {"control": "loop_out",
 "group": "[Channel1]"},
 "67108877": {"control": "ViewMenu_ShowPreviewDeck",
 "group": "[KeyboardShortcuts]"},
 "14": {"control": "flanger",
 "group": "[Channel1]"},
 "67108879": {"control": "ViewMenu_ShowCoverArt",
 "group": "[KeyboardShortcuts]"},
 "33554545": {"control": "LoadSelectedTrack",
 "group": "[Channel1]"},
 "134217842": {"control": "fwd",
 "group": "[PreviewDeck1]"},
 "57": {"control": "filterLowKill",
 "group": "[Channel2]"},
 "67108888": {"control": "FileMenu_Quit",
 "group": "[KeyboardShortcuts]"},
 "100663323": {"control": "OptionsMenu_ReloadSkin",
 "group": "[KeyboardShortcuts]"},
 "167772273": {"control": "eject",
 "group": "[Channel1]"},
 "28": {"control": "pfl",
 "group": "[Channel1]"},
 "33554546": {"control": "LoadSelectedTrack",
 "group": "[Channel2]"},
 "100663325": {"control": "vinylcontrol_mode",
 "group": "[Channel1]"},
 "30": {"control": "beatloop_4_toggle",
 "group": "[Channel2]"},
 "31": {"control": "loop_halve",
 "group": "[Channel2]"},
 "67108896": {"control": "FileMenu_LoadDeck1",
 "group": "[KeyboardShortcuts]"},
 "36": {"control": "start_stop",
 "group": "[PreviewDeck1]"},
 "38": {"control": "back",
 "group": "[Channel1]"},
 "40": {"control": "play",
 "group": "[Channel1]"},
 "33554473": {"control": "cue_gotoandstop",
 "group": "[Channel1]"},
 "33554474": {"control": "crossfader_down_small",
 "group": "[Master]"},
 "43": {"control": "crossfader_up",
 "group": "[Master]"},
 "67108908": {"control": "passthrough",
 "group": "[Channel1]"},
 "45": {"control": "fwd",
 "group": "[Channel2]"},
 "67108910": {"control": "OptionsMenu_EnableLiveBroadcasting",
 "group": "[KeyboardShortcuts]"},
 "33554479": {"control": "cue_gotoandstop",
 "group": "[Channel2]"},
 "29": {"control": "pfl",
 "group": "[Channel2]"},
 "61": {"control": "hotcue_4_activate",
 "group": "[Channel2]"},
 "33554476": {"control": "reverse",
 "group": "[Channel2]"},
 "10": {"control": "beatsync",
 "group": "[Channel1]"},
 "33554484": {"control": "hotcue_1_clear",
 "group": "[Channel1]"},
 "53": {"control": "hotcue_2_activate",
 "group": "[Channel1]"},
 "33554486": {"control": "hotcue_3_clear",
 "group": "[Channel1]"},
 "134217841": {"control": "back",
 "group": "[PreviewDeck1]"},
 "55": {"control": "hotcue_4_activate",
 "group": "[Channel1]"},
 "67108921": {"control": "LibraryMenu_NewPlaylist",
 "group": "[KeyboardShortcuts]"},
 "58": {"control": "hotcue_1_activate",
 "group": "[Channel2]"},
 "33554491": {"control": "hotcue_2_clear",
 "group": "[Channel2]"},
 "167772274": {"control": "eject",
 "group": "[Channel2]"},
 "33554492": {"control": "hotcue_3_clear",
 "group": "[Channel2]"},
 "46": {"control": "play",
 "group": "[Channel2]"},
 "201326621": {"control": "vinylcontrol_cueing",
 "group": "[Channel1]"},
 "33554493": {"control": "hotcue_4_clear",
 "group": "[Channel2]"},
 "100663326": {"control": "vinylcontrol_mode",
 "group": "[Channel2]"},
 "201326622": {"control": "vinylcontrol_cueing",
 "group": "[Channel2]"},
 "100663328": {"control": "FileMenu_LoadDeck2",
 "group": "[KeyboardShortcuts]"}};}
